//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMagicDentPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USRt04_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USRt04_usuario()
        {
            this.USRt05_usuarioRol = new HashSet<USRt05_usuarioRol>();
        }
    
        public long idUsuario { get; set; }
        public string emailUsuario { get; set; }
        public string emailConfirmacion { get; set; }
        public string contraseñaUsuario { get; set; }
        public string numTelefonoUsuario { get; set; }
        public bool lockOutEnabled { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecElimiacion { get; set; }
        public Nullable<long> idUsuarioModificar { get; set; }
        public Nullable<long> idUsuarioEliminar { get; set; }
        public long idEmpleado { get; set; }
    
        public virtual RHUt01_empleado RHUt01_empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USRt05_usuarioRol> USRt05_usuarioRol { get; set; }
    }
}
