//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMagicDentPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt02_archivoEstudioCompl
    {
        public long idArchivoEstudioCompl { get; set; }
        public string descArchivoEstudioCompl { get; set; }
        public string pathArchivo { get; set; }
        public long idEstudioCompl { get; set; }
    
        public virtual CLlt10_estudioCompl CLlt10_estudioCompl { get; set; }
    }
}
